### ISSUE TITLE
Ogg in flash

### ISSUE THREAD

**Issue by ibilon** [HaxePunk/HaxePunk#180]
Since openfl moved away from mp3 on native targets to prefer ogg it may be nice to add support for it in flash.

It seems possible:
* http://bcdef.org/2009/05/13/ogg-in-flash-yes-you-can-now-how-about-wma/
* http://barelyfocused.net/blog/2008/10/03/flash-vorbis-player/

Doing this would allow for an easier sound workflow, no need for conversion mp3-ogg.

**Comment by MattTuttle** [comment]
Adding to trello. https://trello.com/b/JT35cU1i
