### ISSUE TITLE
Pixel-perfect collision and related issues (or the other way 'round)

### ISSUE THREAD

**Issue by azrafe7** [HaxePunk/HaxePunk#194]
Recently I've tried to put together a Pixelmask implementation (my attempts here: https://github.com/azrafe7/HaxePunk/tree/feature/pixelmask). Well, it works, the pixel masks correctly respond to collisions with other masks (flash|cpp|neko) - except for the SlopedGrid that still eludes me, but I'm not familiar with that so.... 

The main problem is that for a pixel-perfect collision to be of some use it must account for rotations, thing that Pixelmask (in the current state) doesn't account for. So thought to chuck that in but... if you're not in BUFFER mode, there is no buffer!
It's not there 'cause in HARDWARE mode it just draws the rotated BitmapData ok... but what about the `target` arg of render, it's still usable?

I could write code with conditional compile flags, but things get messier and messier as there's no common ground for BUFFER and HARDWARE mode.

I know it's not an easy thing to do, but I think that this should be addressed at the core: abstract the rendering process so that we can write simpler code and not worry about the rendering mode.

There's little to no talk around the development of the engine so please comment, the project deserves it.

**Comment by MattTuttle** [comment]
See https://github.com/HaxePunk/HaxePunk/issues/215.
