### ISSUE TITLE
HXP.halfWidth/halfHeight inconsistency relative to scale?

### ISSUE THREAD

**Issue by azrafe7** [HaxePunk/HaxePunk#214]
If screen scale is != 1 they return wrong values (in respect to how I'm used to with FlashPunk, so I could be wrong here).

To reproduce it, test this: https://dl.dropboxusercontent.com/u/32864004/dev/FPDemo/TestHalfSize.zip

Then in `Main.hx` change to: 
```actionscript
        super(200, 100, 60, false);
	HXP.screen.scale = 2;
```

I'd expect to see the rectangle still rendered ~at the center, but it's not.

**Comment by MattTuttle** [comment]
This is fixed an improved in 3.0 with cameras. You will be able to set a scaleMode for the entire scene.
