### ISSUE TITLE
How to check if debug console is enabled

### ISSUE THREAD

**Issue by Marc010** [HaxePunk/HaxePunk#238]
I'm currently working on a lib that makes it easier to use nape with HaxePunk and i wonder how to check if the debug console (the layer list or the log display thingy) is visible.

- HXP.console.visible returns true even if only the update times are shown wich is on by default in debug build anyways

- HXP.console.debug return always true, description says it should return true if console is  in debug mode but i´m not sure what that should mean

**Comment by MattTuttle** [comment]
The console is getting a rewrite in 3.0. Join in the discussion on trello. https://trello.com/b/JT35cU1i
