### ISSUE TITLE
HaxePunk and 3D

### ISSUE THREAD

**Issue by ibilon** [HaxePunk/HaxePunk#295]
Hi @HaxePunk/contributors,

I'm hopping to do 3d games and since I want to keep using haxepunk I'm going to try to transform haxepunk into a 2/3d game engine!
I'm posting this here in case other people think this could be a nice road for haxepunk 3.0

That would mean using openfl's opengl interface, so html5(webgl), windows, linux, mac, android and ios but not flash. So no more flash but no more render-mode and the duplication render/renderAtlas either, everything should be more or less cross-platform.

Since this would require a lot of changes that would be the occasion to check and refine the api. Like checking if there isn't function duplication, moving things around to a more logical place, homogenization of the terms used ...

This wouldn’t be a small project,
starting by defining an api to do 2d&3d (at the same time) the haxepunk way,
there would  be a lot of code to write,
but I think this could add a lot of value to the engine and greatly improve its design.

If you have thoughts or ideas please comment :)

**Comment by ashes999** [comment]
@ibilon is there any final word on whether Flash support is in or out for 3.0 and 4.0?

**Comment by ibilon** [comment]
@ashes999 We'll keep supporting the flash target.

**Comment by MattTuttle** [comment]
Closing in favor of discussion on trello. https://trello.com/b/JT35cU1i
