### ISSUE TITLE
Collisions in 3.0

### ISSUE THREAD

**Issue by ibilon** [HaxePunk/HaxePunk#314]
Following the discussion https://github.com/HaxePunk/HaxePunk/issues/313.

Do you feel that when `Entity.mask` is null the fact that we use an hidden HITBOX object is a problem?
Would it be better to have a default Box mask into the `mask` variable, and then modified (or re-created) by `setHitbox`?

If possible there will be a wrapper around nape (probably) to change between hxp collision and actual physics all without to change code, but with the possibility to use nape stuff like springs, gravity value...

**Planned**:
* Improving Grid beyond solid/not solid. Like the possibility to associate different group (an improvement of `Entity.type`) to different tiles, basically to add an info to collision like this is lava or temporary removing "wall" from the player moveBy solid list.
* No more `sweep` parameter, won't be possible to teleport pass an obstacle if moving too quick
* The x&y parameter of the collisions method will become optional, by default using the actual entity position
* The functions `moveCollideX/Y(e:Entity)` will be replaced with a `collided(c:CollisionInfo)` function, where `c` will hold several information like the entity, where the collision occurred, how much inside did the entity get...
* Creation of an outside mask (the inverse of a box) with helper function to easily prevent object from going out of the camera/scene
* All masks will have an angle property
* The cursor will have a mask property
* An ellipse mask will be added, maybe some other too (requests?) 
* [Advanced feature] the possibility to choose which bounding shape to use between box and sphere, each mask will have a default preferred value, sphere won't have a box bounding anymore.
* [Advanced feature] to improve performances we will include a basic form of quadtree (or maybe another we'll see) and the possibility to either configure it or completely replace it with your own class

Open to feature request/suggestion of course ;)

**Comment by goodpaul6** [comment]
I have a proposition for speeding up/improving Entity.moveBy. In my own engines, instead of checking for collision by sweeping pixel by pixel, I do this:
```
function moveBy(x : Float, y : Float, samples : Int = 2)
{
    var xMov = x / samples;
    var yMov = y / samples;
    
    for(i in 0...samples)
    {
        var e = collide(this.x + xMov, this.y, ...)
        if(e != null)
        {
            if(moveCollideX(e)) break;
            else this.x += xMov;
        }
        else
            this.x += xMov;
    }
    // repeat for y axis
}
```
this way, I could vary the amount of samples based on the magnitude of the velocity, or some other heuristic. It is faster than checking every pixel, but more accurate than simply checking to see if the target position is unoccupied.

**Comment by MattTuttle** [comment]
I know this is an old issue related to 3.0 but I've finally had a chance to sit down and work on collision masks. So here's what most likely will end up in 3.0 if anyone is still interested. It's still very much in an early state so feel free to chime in.

* Decoupling Mask and Entity. Masks should never know about an Entity's position which helps with unit testing and simplifies logic.
* All masks now require a min/max vector which define a bounding box for early-out collision testing. This will also remove the need from having a hitbox on the Entity.
* Separation vectors can be retrieved with an additional function. Entity.collide will still use the faster, current 2.0, method for checking collisions.

My hope is to have a handful of useful Mask classes (Box, Circle, Grid, and Polygon). If you need something more specialized perhaps Nape or another physics library could be utilized.

In my mind, HaxePunk is a framework that helps you work on a game but isn't bloated with tons of classes you'll never use.

**Comment by MattTuttle** [comment]
Closing this in favor of using Trello for TODO items. If you want access to comment on the roadmap let me know. https://trello.com/b/JT35cU1i
