### ISSUE TITLE
Feature request : animated tiles in tilemaps

### ISSUE THREAD

**Issue by matrefeytontias** [HaxePunk/HaxePunk#348]
As far as I know, there is no way of using animated tiles with Tilemap instances. For example, in a Pokémon clone, it would be nice to be able to use animated water tiles the same way you would use non-animated ground tiles.

Maybe define non-animated objects as animated objects that only has one frame, like you do with Spritemaps. Actually, a way of implementing this would probably be to build a tilemap using a tileset exclusively made out of Spritemaps, though I don't know what impact that will have on performances.

**Comment by ibilon** [comment]
That's definitively a feature we need.

I added it to the api specification for haxepunk 3.0,
you can see the TileMap class here: https://github.com/HaxePunk/HaxePunk/blob/release-3.0.0/haxepunk2d/graphics/TileMap.hx

For a "normal" tile you'd do `myTileMap.setTile(column, row, index);` and for an animated one `myTileMap.setTileAnimation(column, row, [index0, index1, index2], frameRate);`.
Similarly for `setRectangle` and `setRectangleOutline`. 
What do you think of the syntax?

Note: It's now yet in all the function in the file I linked but you can refer to the tileset with either an index of the tile or it's position (column, row).
So `myTileMap.setTile(column, row, [tileX, tileY]);` or using explicitly the Point object `myTileMap.setTile(column, row, new Point(tileX, tileY));`, same for animated tiles.

**Comment by matrefeytontias** [comment]
That looks good, but it's not complete in my opinion. There should be a way to define static and animated tiles altogether in functions such as loadFrom2DArray or loadFromString, although I can't really think of a format that would not produce huge data for small tilemaps ... To take the example of Pokémon again, nobody would actually insert every water tile manually with X calls to a function.

I'm rather thinking about how animations work in spritemaps: something like `myTilemap.setAnimated(tileID:Int, frames:Array<Int>, fps:Float)` and `myTilemap.setStatic(tileID:Int)`. With this, you can easily define animated and static tiles in one map:

```Haxe
// The tileset would have "base" tiles from 0 to 15, and additional frames from 16 to 63 for example. It'd be up to the user to define how his tileset is constructed
var myTilemap = new Tilemap("graphics/tileset.png", width, height, tWidth, tHeight);
myTilemap.setAnimated(2, [ 2, 18, 34, 50 ], 20);
myTilemap.setTile(0, 0, 2); // when a 2 is encountered in the tilemap data, the tile animates with images 2, then 18, then 34, then 50 from the tileset.
myTilemap.setTile(1, 0, 3); // a tile is static by default
```
Is that better ?

**Comment by MattTuttle** [comment]
I'd rather not bloat the Tilemap class with animation checks. That is overkill for most use cases and would be better as a subclass of Tilemap like AnimatedTilemap. It's a good idea though.

**Comment by ibilon** [comment]
@matrefeytontias Makes sense, I added a setAnimation function.
@MattTuttle You're right, created a subclass.

**Comment by matrefeytontias** [comment]
Alright so while this exists, I'm asking a few questions.
I'm trying to do a replacement for the non-existing animated tiles, and right now I'm doing it by blitting extra spritemaps on top of the tilemap. I guess it's a horrible way to do it, plus it doesn't even look good on-screen since the spritemaps and the tilemap don't fit well (maybe that's a bug ? I don't know).
So yeah, question is, while waiting for the feature, what is the best way to do it ?

**Comment by matrefeytontias** [comment]
Actually never mind I'm stupid. Didn't think of using setTile.

**Comment by MattTuttle** [comment]
I believe this was recently added to dev. I'll add it to the roadmap on trello. https://trello.com/b/JT35cU1i
