### ISSUE TITLE
Incorrect example on Imagemasks.hx

### ISSUE THREAD

**Issue by jci** [HaxePunk/HaxePunk#359]
For the code used on Imagemasks.hx the following appears:

  * class Object extends Entity
{
 public function new()
    {
       super();
    var sprite = new Image("myimage.png", 100, 100);
      graphic = sprite;
        mask = new Imagemask(sprite);
          mask.assignTo(this);
      }
  }

This does not work as mask does not have the assignTo method.

**Comment by ibilon** [comment]
Oh indeed there's no such function anymore,
just remove the line,
I'll update the documentation.
