### ISSUE TITLE
OpenFL 3.0 Beta issues

### ISSUE THREAD

**Issue by vance** [HaxePunk/HaxePunk#361]
OpenFL 3.0 beta 3

<b>Runtime errors while commenting out comiple errors:</b>

GraphicsRenderer.hx:1636: Warning: shape too complex to fill
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Called from sys.io.FileOutput::$statics line 1
Called from ApplicationMain::main line 166
Called from ApplicationMain::create line 99
Called from lime.app.Application::exec line 158
Called from lime._backend.native.NativeApplication::exec line 102
Called from lime._backend.native.NativeApplication::handleRenderEvent line 59
Called from lime.app.Application::render line 519
Called from openfl.display.Stage::render line 895
Called from openfl._internal.renderer.opengl.GLRenderer::render line 274
Called from openfl._internal.renderer.opengl.GLRenderer::renderDisplayObject line 291
Called from openfl.display.DisplayObjectContainer::__renderGL line 865
Called from openfl.display.DisplayObjectContainer::__renderGL line 865
Called from openfl.display.DisplayObjectContainer::__renderGL line 861
Called from openfl.display.DisplayObject::__renderGL line 1124
Called from openfl._internal.renderer.opengl.utils.GraphicsRenderer::render line 805
Called from openfl._internal.renderer.opengl.utils.GraphicsRenderer::renderGraphics line 837
Called from openfl._internal.renderer.opengl.utils.StencilManager::pushBucket line 72
Uncaught exception - Invalid field access : length
Done(1)

<b>Compile Errors in Neko</b>

<b>HaxePunk Team or OpenFL Team</b>

<b>Engine.hx line 205</b>
flash.display.Stage.shouldRotateInterface = function(orientation:Int):Bool {
			if (HXP.indexOf(HXP.orientations, orientation) == -1) return false;
			var tmp = HXP.height;
			HXP.height = HXP.width;
			HXP.width = tmp;
			resize();
			return true;
		}

<b>Line 121 of XHP.hx</b>
	public static function resizeStage (width:Int, height:Int)
	{
		#if (cpp || neko)
		HXP.stage.resize(width, height);
		resize(width, height);
		#elseif debug
		trace("Can only resize the stage in cpp or neko targets.");
		#end
	}

<b>Line 123 of Text.hx</b>

if (!Reflect.hasField(options, "align"))     options.align     = TextFormatAlign.LEFT;

**Comment by scriptorum** [comment]
It looks like they flipped the switch on the next/legacy code. For now you should be able to compile with the OpenFL beta by adding `-Dlegacy` to your command line.

**Comment by vance** [comment]
Thanks! I tried with -Dlegacy and get the same errors. I'm going to downgrade to 2.2.8. I seem to always have problems with text or fonts when changing targets. I'll wait till it's stable.

**Comment by scriptorum** [comment]
Hrm. I compiled the demos using -Dlegacy and the errors went away for me.

**Comment by vance** [comment]
Oh, you're totally right. My IDE was not saving preferences. I compiled it fine in the shell and it worked. Dang it, FD.

**Comment by ibilon** [comment]
I've been working on compatibility with openfl3,
got a couple of fixes on my computer,
I'll push them.
