### ISSUE TITLE
unable to parse haxelibinfo macro

### ISSUE THREAD

**Issue by stasuss** [HaxePunk/HaxePunk#362]
having issue on linux system. upon compilation it just throws "haxelib.json" not found.
looking inside HaxelibInfo.hx I figured out that result var remains empty.
I fixed it with changing line 61 to this
Json.parse(sys.io.File.read(lines[0] + "/haxelib.json").readAll().toString());

but i think it ist lame fix, so may be developers can find the real solution.

also have tested on win virtualbox. there is all the same, except more - version part of path is passed with / instead of \, so it is also needed to replace backslashes here, but it is not necessary for me.

haxepunk 2.5.3
haxelib_client 3.2.0-rc3

**Comment by ibilon** [comment]
Haxelib 3.2 changed sightly the output of the path command,
it's not `-DHaxePunk` anymore but `-DHaxePunk=2.5.3`.
