### ISSUE TITLE
Feature Request: Noise Functions

### ISSUE THREAD

**Issue by zauberparacelsus** [HaxePunk/HaxePunk#365]
The feature I'd like to request is the addition of functions that generate 2D or 3D noise, which is useful for generating procedural game content, such as graphics or pseudo-random levels.  Minecraft, for example, utilizes Perlin noise for world generation.

Notable algorithms include Perlin, Musgrave, Wave, Worley (aka voronoi), and Simplex.  The last one, Simplex, is much faster than Perlin.  However, it should be noted that 3D and 4D Simplex noise implementations are patent-encumbered and require licensing.

Not a problem presently for HaxePunk, since it is a 2D engine and 2D simplex noise is not patented, though I recall reading that there were plans for adding 3D support in HaxePunk 3.0

**Comment by bendmorris** [comment]
For Perlin noise at least there is BitmapData.perlinNoise:

http://www.openfl.org/documentation/api/openfl/display/BitmapData.html#perlinNoise

Previously this had issues on non-Flash platforms - not sure if it's working now, but worth a try.

**Comment by zauberparacelsus** [comment]
Doh.  Should have checked the docs, lol

**Comment by MattTuttle** [comment]
I think this should be considered for addition in HaxePunk 3.0. I'll add it to the roadmap in trello. https://trello.com/b/JT35cU1i
