### ISSUE TITLE
Image.drawPolygon memory leak?

### ISSUE THREAD

**Issue by SunShiranui** [HaxePunk/HaxePunk#366]
Drawing different polygons using Image.drawPolygon each frame and assigning them to an entity's graphic eventually leads to a crash (no errors on console). I suspect this may be because of a memory leak. 

Some more information here: http://forum.haxepunk.com/index.php?topic=935.0

**Comment by scriptorum** [comment]
My first thought is we should not auto-assign a name when we make a new AtlasData and no name is supplied. Add null checks for _name, do not cache in _dataPool. Then when entity.graphic is nulled or changed, dynamic bitmaps should eventually be garbage collected: Image -> _region -> _parent -> AtlasData -> _tilesheet -> BitmapData.

**Comment by scriptorum** [comment]
Okay, that's what I did, fixing the test code provided by @SunShiranui, and the examples demo ran correctly afterward targeting desktop.

Reopen this ticket if I caused a regression issue anywhere, or you still see memory leaks related to this.
