### ISSUE TITLE
Lag when calling Data.save()

### ISSUE THREAD

**Issue by rpidstryhach** [HaxePunk/HaxePunk#375]
Flash build significantly lags for about a second everytime `Data.write()` is called. Issue confirmed on Windows/Firefox, though not on every system. On my Win8.1 + latest Firefox/Flash it's just fine, on another computer with the same versions of software installed it lags. Any ideas what might cause this? Chrome and FF on OS X is ok. 
Thanks.
UPD: It's `Data.save()` causing lags.

**Comment by ibilon** [comment]
It really shouldn't, that's just a map set.
https://github.com/HaxePunk/HaxePunk/blob/dev/com/haxepunk/utils/Data.hx#L99

Maybe that's another thing, if you comment the `Data.write` call do you still get the lag?

**Comment by rpidstryhach** [comment]
Yeah, that's why I was confused at first. 
UPD: My fault, I tested a little bit more and it turns out that `Data.save()` is causing this, not writing.

**Comment by rpidstryhach** [comment]
Ok, so I think I have a bigger picture now. On my Win/Firefox system where it's not lagging - it doesn't actually saving anything at all. Idk why, yet. Also, it turned out being not browser specific, Chrome on Windows lags too, though barely noticeable. I believe it lags on my mac as well, but due to fast SSD it's impossible to notice. I remember having similar issues with Flash's SO (and this is essentially it, right?), so the only workaround might be flushing memory in a separate thread if possible.

**Comment by ibilon** [comment]
Yes it's basically just shared object.

Making the flush call in a separate call is easy enough, not sure how that will affect the state of the SO and if it can't lead to problems.
