### ISSUE TITLE
Type not found: JoystickEvent

### ISSUE THREAD

**Issue by rpidstryhach** [HaxePunk/HaxePunk#380]
I posted an issue with more details here: 
https://github.com/clemos/haxe-sublime-bundle/issues/257
Got this problem with autocompletion using Haxe bundle for Sublime Text. Everything works fine when I'm not using HaxePunk. Any ideas?
Thanks

**Comment by MattTuttle** [comment]
I've had issues with autocomplete in Sublime Text before. If I remember correctly it had to do with the target being used for autocomplete and switching it to neko or c++ seemed to work for me. I think it was in a configuration file.

**Comment by johnhatch** [comment]
I've been having this issue as well. It seems `JoystickEvent` was moved to `openfl_legacy` and has been deprecated: http://www.openfl.org/blog/2015/10/06/october-update/ 
> The old JoystickEvent has been deprecated, I hope that you enjoy the new Gamepad or Joystick API, or use the GameInput API for Flash compatibility. OpenFL Legacy will continue to use only JoystickEvent.

I'd imagine `utils/Input` needs to be reworked to use `GameInput` instead?

**Comment by rpidstryhach** [comment]
Yeah, that's it. How did I miss that? I'm not using any Joystick functionality so commenting out import helps with Sublime Text autocompletion. But this has to be reworked. Thanks, I'll close another issue, as this is clearly HaxePunk related.

**Comment by r3d9u11** [comment]
Just replace conditions 	#if (cpp || neko) #if (openfl && (cpp || neko)) with #if (openfl_legacy && (cpp || neko)) at source haxelib/HaxePunk/2,5,6/com/haxepunk/utils/Input.hx

it work's for my vim autocompletion

(conflict between conditions in haxelib/openfl/3,4,0/openfl/events/JoystickEvent.hx & in haxelib/HaxePunk/2,5,6/com/haxepunk/utils/Input.hx before definition type JoystickEvent)

**Comment by johnhatch** [comment]
@r3d9u11 I didn't think of changing the conditions, no more errors here, thanks!

@rpidstryhach Yeah I'm not using any joysticks either, guess if joysticks are ever needed then openfl legacy can be used.

Seems the issue of implementing the new Joystick class still stands, but at least autocomplete works now :)

**Comment by ibilon** [comment]
Changing the condition will help, but it's also hiding the real problem: you need the completion to be in openfl_legacy mode to be consistent with the openfl version used by haxepunk.

Otherwise you may end up using parts that are openfl next only, by default you'll end up with compilation errors, and even if you pass `-Dnext` to override the version used by haxepunk you'll find out that the compatibility with next is not good.
