### ISSUE TITLE
User feedback

### ISSUE THREAD

**Issue by markknol** [HaxePunk/HaxePunk#384]
https://www.reddit.com/r/gamedev/comments/44f5lx/anyone_have_experience_shipping_with_haxe_and_can/

I just found this via Twitter, not sure if you've seen it.   Its quit a long thread but mentions some issues with installation etc, maybe something to put on the roadmap.

**Comment by MattTuttle** [comment]
Unfortunately this goes a lot deeper than just HaxePunk. It's the very reason I get frustrated coming back to Haxe development. Haxelib doesn't let us specify versions that work with our libraries so updating them breaks old code. I'm actually curious why one guy is claiming there are a bunch of memory leaks...

**Comment by markknol** [comment]
Ok thanks for letting know, you can close the issue.

Btw I'm no expert but I think Travis can help with testing the library with different Haxe versions? This is a bit the other way around but then you could be compatible with multiple versions.
