### ISSUE TITLE
Any clearTile function broken with Tilemap

### ISSUE THREAD

**Issue by matrefeytontias** [HaxePunk/HaxePunk#385]
Setting a tile in a Tilemap to -1 in any way seems to not work at all and sets it to 0 instead. Tested functions include:

```
setTile(x, y, -1)
setRect(x, y, w, h, -1)
clearTile(x, y)
clearRect(x, y, w, h)
```

Those all set the specified tiles to 0 instead of -1.

**Comment by scriptorum** [comment]
Hrm, @matrefeytontias, I just tested this with a fresh build targeting flash and mac and it's working for me.

```haxe
map = new Tilemap("graphics/runningcat.png", 1024, 1024, 512, 256, 0, 0, false);
map.loadFromString("0,1 2,3 4,5 6,7", ",", " ");
map.clearTile(0, 0); // eliminate first cat
trace("Tile at 0,0:" + map.getTile(0,0)); // prints MainScene.hx:22: Tile at 0,0:-1
```
(Full example at https://gist.github.com/scriptorum/ae60a9dd3f0ba93871249be1295022d2)

Can you share a complete example that fails for you?

**Comment by MattTuttle** [comment]
The tile index can't be negative because of the code in setTile `index %= _setCount`. The help text should probably be changed.

**Comment by scriptorum** [comment]
> The tile index can't be negative because of the code in setTile index %= _setCount

I thought that too, but languages vary on how they handle a negative dividend with modulo. I'm using Haxe 3.2.1 and my tests on Mac and Flash produced a negative result. I also got that outcome from http://try.haxe.org/#A9DA7. I wonder if there is an inconsistency between haxe targets?

> The help text should probably be changed.

No, -1 is a legitimate value for Tilemap, it indicates the cell should be transparent. [Blame me for that.] (https://github.com/HaxePunk/HaxePunk/commit/3bb778f32e61a3c70eae70a2091f582bc1444a06) 😀 

Worst case, we could check for -1 ala `if(index >=0) index %= _setCount;`. @matrefeytontias what platform are you targeting, and what is your haxe version?

**Comment by matrefeytontias** [comment]
I was targetting C++ with the latest version of Haxe, 3.2.1 I believe.
