### ISSUE TITLE
Haxepunk not compatible with openfl +4.0   (Tilesheet class removed)

### ISSUE THREAD

**Issue by xmorpher** [HaxePunk/HaxePunk#387]
I just updated openfl to 4.0.0 and i got this error:
`D:/HaxeToolkit/haxe/lib/HaxePunk/2,5,6/com/haxepunk/graphics/atlas/AtlasData.hx:11: characters 7-31 : Type not found : openfl.display.Tilesheet`

i think that "Tilesheet" class was removed from openfl

**Comment by xmorpher** [comment]
maybe if the Tilesheet class is added to haxepunk
it will be compatible again?

**Comment by MattTuttle** [comment]
I'm not sure it'll be that easy. The Tilesheet class used to map to c++ functions and they probably changed the way those work. My suggestion would be to use OpenFL 3.x unless you want to figure out how to move to the new Tilemap class.

**Comment by bendmorris** [comment]
Tilemap doesn't have all the same features as Tilesheet did. For now I think we should lock to OpenFL 3.6.1 and Lime 2.9.1 as Flixel is doing. Long term we do need to figure this out - either add a separate rendering path for newer versions of OpenFL (ideal, if there's a working alternative) or else drop OpenFL for NME.

**Comment by voec** [comment]
Do you know the exact reasons why they changed it? They must have realized that they would break a majority of the frameworks that use OpenFL?

**Comment by ibilon** [comment]
The openGL renderer was changed, and since it needed to be recoded Joshua choose to improve it instead.

**Comment by bendmorris** [comment]
Will be fixed by https://github.com/HaxePunk/HaxePunk/pull/406, please give that a try with OpenFL 4.

This basically required reimplementing drawTiles in HaxePunk (not using Tilemap) and Flixel is doing something similar. Hope they think about how downstream projects will be affected before doing something like this in the future.
