### ISSUE TITLE
Add rotation center to Canvas/Backdrop

### ISSUE THREAD

**Issue by matrefeytontias** [HaxePunk/HaxePunk#388]
I didn't try, but I'm pretty sure it's possible to achieve rotation around any point if you use an Entity and its Graphic' coordinates cleverly. Still, there should be a more practical way to achieve that. In particular, I'm trying to rotate a Backdrop, and just using the `angle` property (inherited from `Canvas`) isn't enough, as it rotates around its top-left pixel.

**Comment by bendmorris** [comment]
It's possible with Image and anything that uses Image to render, but Backdrop unfortunately does not. This could be solved by either adding an origin to Backdrop, or (even better IMO) refactoring Backdrop to be a subclass of Image.

**Comment by bendmorris** [comment]
Added in https://github.com/HaxePunk/HaxePunk/commit/3d52a50f6748d5a3ea403b8092eea987e2080673
