### ISSUE TITLE
HaxePunk 4.0

### ISSUE THREAD

**Issue by bendmorris** [HaxePunk/HaxePunk#392]
@HaxePunk/contributors, @voec, @matrefeytontias - please tag anyone else who might be interested.

Hi everyone! HaxePunk is dead - no new development, issues/PRs mostly not being looked into. Since there's nothing happening now, I wanted to propose a specific vision for the future and see what people think.

Back in 2014 part of the team began working on a "HaxePunk 3.0" which turns it into a combined 2D/3D engine. This was a complete rewrite of the engine with a lot of big breaking changes, and it looks like it has stalled; there's been no movement on Trello this year: https://trello.com/b/JT35cU1i/version-3-0. Unfortunately this made it difficult for other contributors unrelated to the 3D effort to add new features. For me at least, there was concern that effort would be wasted since there were so many upcoming changes that might make my work break or become obsolete.

Around that time, I started working on my own fork of HaxePunk (https://github.com/bendmorris/haxepop) which gave me a testbed for some experimental changes in the original 2D engine. Some of these worked out well, others did not, but I think I have a good basis now on which can be merged into HaxePunk. I've also recently been working with HaxeFlixel which I've found has a lot of the same features I had developed in my fork.

I propose **moving toward a 4.0 release** (skipping 3.0) which is an enhanced version of the original 2.X line. 3.0 doesn't need to be scrapped, but since it's a separate effort it can continue as a separate project if there's still interest.

Here's a partial list of changes that could make it into this release:
- Screen scaling modes to precisely control how the game is transformed when you resize the screen.
- Camera objects, with multiple camera support for split screen, HUDs, etc. HaxeFlixel does this very well.
- Get rid of the "com" package - `import haxepunk.*`
- A unified Input system, so Mouse/Gesture/Keyboard/Controller etc. use a consistent API and can seamlessly work together.
- An EntityList for grouping entities and manipulating or colliding with them together.
- Pixel snapping which can be toggled on/off.
- Support for 9 slice graphics.
- A simple layout/UI library.
- Animated Tilemaps - we should review and merge @voec's work on this: https://github.com/HaxePunk/HaxePunk/pull/377.
- A decent number of bug fixes as well.
- More tests and demos.

The goal would be to push for a new 4.0 release with these changes by the end of the year.

One more thing to consider:
- OpenFL has removed drawTiles completely from its API, so HaxePunk will not work with new versions of OpenFL in the near future. One way around this is to use NME, which is still active and very stable; the downside is that we lose some targets which NME doesn't support, particularly HTML5. Using NME shouldn't rely any changes in the engine, as it generally works out of the box with OpenFL projects.

I wanted to see if there's enough interest still to sustain continued work. What does everyone think? Should we start working on this?

**Comment by matrefeytontias** [comment]
I'm interested. I've been adding a number of bugfixes and additional features in HaxePunk over the last few months - mostly having to do with Imagemask and Pixelmask working with nearly no other mask outside of Flash and Backdrop reacting weirdly to scaling. As a game dev, I don't know how much time I'll have to dedicate to this, but I would sure be sad to see HaxePunk completely die. I have been using it for a while, and apart from the many missing features I had to implement myself (which by the way gave me a great understanding of the lib) which were really frustrating to stumble upon, I rather like the lib. I'd be happy to be a part of its future.

**Comment by Anheurystics** [comment]
I'm genuinely interested in helping out with continuing HaxePunk, but I have no idea on where to start with the code-- what needs fixing or adding, etc.

**Comment by voec** [comment]
Hey!
This sounds great. I would be glad to contribute wherever I can be of use.

I think there are a lot of things that could be cleaned up and improved. Here are a couple of other suggestions of the top of my head:
- Improving the way input from controllers from different manufacturers are handled (I'll make an issue that explains this further)
- Maybe improving the console a bit more, taking some inspiration from the FlashPunk? http://developers.useflashpunk.net/t/updating-the-flashpunk-console/1351

Regarding the issue with OpenFL: I always thought of OpenFL being pretty much the continuation of the more stale NME, so this sounds a bit like a backwards step. But it seems this has changed lately?
I don't know, I would be interested in knowing how HaxeFlixel and others are planning on handling this change?

Apart from this I would be happy to revitalize the effort to update the HaxePunk website. I think a 4.0.0 release would be a perfect time for that. :)

**Comment by bendmorris** [comment]
I created a Gitter chat: gitter.im/haxepunk/haxepunk, does anyone prefer Slack? I haven't played with Gitter integrations, not sure how they compare.

@matrefeytontias: your fixes have been merged. Welcome aboard!

@Anheurystics: beyond the ideas that I listed (which I'm working on, but feel free to jump in) I think basically any open issues (we don't have a lot, possibly due to inactivity) or any other new features you would like to see in the engine would all be useful.

@voec: I liked your website mockups, would love to use one of them.

re: controllers, there's an SDL function which gives the ID of the controller so you can differentiate between different types. I added this to openfl-native at some point and it might've been lost in the transition to Lime. I'll look into it.

re: NME, that was definitely the case for a while, but it has recently become active and started releasing again. Since their focus is on stability, I think we should try to support both, so that breaking changes in one aren't a show stopper. Experimenting with it and flixel, I've found better performance and fewer bugs than in OpenFL "legacy."

HaxeFlixel is working on implementing their own renderer (not using Tilemap either.) I haven't looked at it in much detail but let's see if we can borrow anything from their implementation. https://github.com/HaxeFlixel/flixel/pull/1940

**Comment by xmorpher** [comment]
Great! it would be sad if Haxepunk stays obsolete when is a great tool to develop games and apps!

i like the idea of keep both projects separate (haxepunk and haxepunk-nme)

**Comment by bendmorris** [comment]
I don't think there's any reason to keep them separate, they would be identical. NME works transparently with OpenFL - you don't even have to change the include.xml or remap the imports, it does that for you.

**Comment by TaylorAnderson** [comment]
just popping in to say, although i dont think i can be much use in the effort (lack of time + limited tools-dev experience) i am so glad there is a drive to bring haxepunk back! i've been using it this whole time and it's been super sad to see the community / development effort die.

**Comment by Tembac** [comment]
HaxePunk seems like a good tool but from the beginning it looks very similar to Flixel. Wouldn't it be better to join forces with HaxeFlixel so we can get best from both worlds?

**Comment by ibilon** [comment]
The api/way to use is different,

but having haxepunk use haxeflixel instead of openfl internally is kind of weird but it could work.

**Comment by xmorpher** [comment]
@Tembac : they're different, both are great frameworks, i have used both,
and i think it's better to have both...
It's always better to have options

**Comment by TaylorAnderson** [comment]
i've used both flashpunk/haxepunk and haxeflixel for many projects and i would definitely not want the two to overlap. haxeflixel has a very different workflow than haxepunk, and i prefer haxepunk a lot more

**Comment by bendmorris** [comment]
I agree with @xmorpher and @TaylorAnderson. They're different and competition (not in a negative way, just coexisting and serving the same purpose) makes both engines better. What I've seen over time is that each one tries out its own ideas, and if they work, the other adopts them in some form. I think this is better than trying to consolidate into one API, one way of doing things.

From another perspective, if we stop updating HaxePunk, people are still going to keep using it. So we might as well keep improving it for them.

**Comment by SunShiranui** [comment]
I'm happy to see new activity on HaxePunk - I'd been looking around for alternatives since development seemed to have stopped. I'll see if I can find ways to help, though I've never worked on engines before.

Going back to features we'd like to see, here are some I think would be useful:

- Hardware accelerated post processing effects (e.g. blur, more blending modes), not restricted to fullscreen, perhaps shader support?
- Already mentioned above, but camera support with zoom and rotation would also be nice

**Comment by scriptorum** [comment]
Thanks for pumping some energy into this project, @bendmorris. I haven't put much time into HaxePunk lately; been expending brain cells on Unity.

For me, the big missing feature is nested/grouped entities. In Unity and OpenFL you can simply make any entities (GameObject/Sprite) children of another entity, and the hierarchical position/scale/rotation is calculated for you. [EntityList](https://github.com/HaxePunk/HaxePunk/blob/dev/com/haxepunk/EntityList.hx) touches upon the solution, but seems to be modeled more after [FlxGroup](http://haxeflixel.com/documentation/flxgroup/).

I would love to see more 3D/hardware/lighting features, an editor to assist in the placement of entities and test particle effects, and multiple cameras. At this point I feel like we're lagging behind HaxeFlixel. I don't see any benefit in joining forces - if you want to use HaxeFlixel, go use it, it's a great product. But I do see value in shifting HaxePunk down a different path, which is what I liked about the plans I saw for HP 3.0.

**Comment by bendmorris** [comment]
We could definitely allow entities to have other entities as parents, and introduce local/global versions of position/scale/rotation. I think we could even do it without any breaking changes.

I would love to see more hardware effects - I think the challenge is how to introduce those types of features and still maintain our clean design and ease of use for 2D games. Multiple cameras using separate sprites is on my short term roadmap (need it for a game I'm trying to port.)

**Comment by bendmorris** [comment]
P.S. I wrote EntityList back in 2014 and had never heard of FlxGroup before 😛 https://github.com/bendmorris/haxepop/commit/3efab56f95b143e1cd50001ea0087a7374cef5ed

**Comment by azrafe7** [comment]
Great to see this coming back to life again! That's **wunderbar**!!! :congratulations: 

I've been following the progress from a distance with the secret hope to be able to contribute concretely at some point. Been away from the project for some time, but I really hope to get back and up-to-speed soon.

Many thanks to @bendmorris (great work!!) and to all the contributors tooo.

Cheers, and keep it up! \o

**Comment by infidel-** [comment]
And the forum is full of spam. I'd love for development to continue at least for not having to migrate my long-in-development project to another engine :)

I also missed something, does HaxePunk actually support HTML5? I've tried it and it failed with some error for me.

**Comment by MattTuttle** [comment]
I cleaned up the spam and upgraded the forum software. Should be good for another 6 months. :smile:

**Comment by bendmorris** [comment]
>I also missed something, does HaxePunk actually support HTML5? I've tried it and it failed with some error for me.

It does, using OpenFL's WebGL renderer. I recently used it for Ludum Dare. Can you open an issue with the problems you're encountering?

**Comment by infidel-** [comment]
@bendmorris I'll check it out once more.

**Comment by infidel-** [comment]
@bendmorris Hey, HTML5 actually does work and scales the window much better than the binary version. In the binary raw OpenFL windows and text stays the same size by default.

**Comment by bendmorris** [comment]
Closing this issue as we're moving towards 4.0!

**Comment by TaylorAnderson** [comment]
!!!!!!
