### ISSUE TITLE
Seeking Location for New Game .md & .jpg Files

### ISSUE THREAD

**Issue by NBumgardner** [HaxePunk/HaxePunk#397]
# Game PR Questions
I was in a team which made a game in HaxePunk, and I'd like to add the *markdown* and *image* files so it can join the [HaxePunk list of games](http://haxepunk.com/games/).

**Q1:** Where do those two files go?
**Q2:** Should my pull request be to the `dev` branch?

In Feb. 2015 there was a `games` folder and `img` folder for Games commits. See [#3ea4c23](https://github.com/HaxePunk/haxepunk.com/commit/3ea4c236b189d3e46b32a9fb44a00ab4b4c2931b).

**Comment by bendmorris** [comment]
The website and that commit are actually in a different repo: https://github.com/HaxePunk/haxepunk.com. You can make your PR there.

**Comment by NBumgardner** [comment]
Thank you. I'll close this issue after I make a PR there.

**Comment by NBumgardner** [comment]
[PR #19 was made in the other repo and awaits approval!](https://github.com/HaxePunk/haxepunk.com/pull/19)
