### ISSUE TITLE
New features for 2.6

### ISSUE THREAD

**Issue by bendmorris** [HaxePunk/HaxePunk#405]
- [X] An EntityList for grouping entities and manipulating or colliding with them together.
- [X] Scene stack with transparent scenes for popups or menus.
- [x] More tests and demos.
- [X] NME compatibility.
- [X] Emitter improvements - scale, angle, trails.
- [x] Custom cursors.
- [x] OpenFL 4 support.
- [X] Screen scale modes.
- [x] Rewrite the Preloader without Tilesheet

**Comment by EdgarMagdaleno** [comment]
Started working on the custom cursors, however I think an amazing change (and I think is has been mentioned before) is adding a center of rotation for hit boxes. Its REALLY inconvenient when your sprites have to rotate and you either end up not using pixelmasks or making a separate one for each milestone of rotation. 

That'd be a good addition to the list IMO.

**Comment by matrefeytontias** [comment]
Doesn't that already exist ? IIRC, masks use _parent.origin(X | Y) in the collision code.

**Comment by bendmorris** [comment]
There are a lot of fixes/enhancements needed for masks. I think we should push that to 4.0 and start by added comprehensive tests to make sure we cover all cases.
