### ISSUE TITLE
Enabling fixed framerate in Main breaks the display

### ISSUE THREAD

**Issue by matrefeytontias** [HaxePunk/HaxePunk#425]
I suspect that this is caused by the fact that up to this point, all durations were in seconds when HXP.fixed is false and in frames when HXP.fixed is true. This is obviously a design flaw, but because it has always been like this, the library depends on it working like this to be functional.

Main.hx:
```Haxe
import com.haxepunk.Engine;
import com.haxepunk.HXP;

class Main extends Engine
{

	override public function init()
	{
#if debug
		HXP.console.enable();
#end
		HXP.fixed = true;
		HXP.scene = new MainScene();
	}

	public static function main() { new Main(); }
}
```
MainScene.hx:
```Haxe
import com.haxepunk.Scene;
import com.haxepunk.graphics.Image;

class MainScene extends Scene
{
	override public function begin()
	{
		addGraphic(Image.createRect(50, 50, 0xffffff));
	}
}
```

**Comment by bendmorris** [comment]
This seems related to TileShaderRenderer also, because your example works fine with NME and OpenFL 3.6.1. Probably due to that renderer's timing being slightly different under fixed timestep. I think the fix for https://github.com/HaxePunk/HaxePunk/issues/418 should also take care of this.

**Comment by bendmorris** [comment]
Resolved by https://github.com/HaxePunk/HaxePunk/pull/426
