### ISSUE TITLE
Sound generally malfunctioning with Neko target

### ISSUE THREAD

**Issue by matrefeytontias** [HaxePunk/HaxePunk#429]
I'm pretty sure this is related to OpenFL, because it doesn't appear on any other target that I tried (including HTML5).

```Haxe
import com.haxepunk.Scene;
import com.haxepunk.Sfx;

class MainScene extends Scene
{
	override public function begin()
	{
		new Sfx("audio/music.ogg").loop();
	}
}
```

It breaks and stops playing after some repetitions. You can see that in the Sfx, `_channel.position` is reset to 0 at some point and won't move, although the channel is indeed active.

**Comment by bendmorris** [comment]
Not much we can do about this. Since Sfx is a thin wrapper over OpenFL's sound functionality, you should open this issue with them.

**Comment by bendmorris** [comment]
https://github.com/openfl/openfl/issues/1368

**Comment by bendmorris** [comment]
Closing as an OpenFL/Lime issue.
