### ISSUE TITLE
Endless compilation loop

### ISSUE THREAD

**Issue by infidel-** [HaxePunk/HaxePunk#434]
Took me some time to find but it looks like Haxe goes into the endless compilation loop if there is a local version of assets/font/04B_03__.ttf file

Haxe 3.4.0rc1, openfl 4.5.2, lime 3.5.2, HaxePunk 2.6.0

Steps to reproduce:
```
haxelib run HaxePunk new MyProject
```

Copy 04B_03__.ttf from <haxelib>/HaxePunk/2,6,0/assets/font

```
openfl build project.xml windows -verbose
```

First I see that the font file is detected twice:
```
 - Detecting font name: /home/infidel/haxelib/HaxePunk/2,6,0/assets/font/04B_03__.ttf -> "04b03"
 - Detecting font name: assets/font/04B_03__.ttf -> "04b03"
```

Then it tries to run a build command:
```
 - Running command: haxe bin/windows/neko/release/haxe/release.hxml
```

And it just endlessly uses CPU doing nothing. If I break the execution, I see a long exception stack relating to lime build macro:
```
/home/infidel/haxelib/lime/3,5,2/lime/system/CFFI.hx:47: characters 9-41 : Called from
/home/infidel/haxelib/lime/3,5,2/lime/text/TextLayout.hx:9: characters 1-7 : Called from
/usr/share/haxe/std/haxe/macro/Context.hx:381: characters 9-37 : Called from
/usr/share/haxe/std/haxe/macro/ComplexTypeTools.hx:51: characters 28-71 : Called from
/home/infidel/haxelib/lime/3,5,2/lime/_macros/CFFIMacro.hx:60: characters 57-75 : Called from
/home/infidel/haxelib/lime/3,5,2/lime/system/CFFI.hx:47: characters 9-41 : Called from
/home/infidel/haxelib/lime/3,5,2/lime/_backend/native/NativeWindow.hx:13: characters 1-7 : Called from
/usr/share/haxe/std/haxe/macro/Context.hx:381: characters 9-37 : Called from
/usr/share/haxe/std/haxe/macro/ComplexTypeTools.hx:51: characters 28-71 : Called from
/home/infidel/haxelib/lime/3,5,2/lime/_macros/CFFIMacro.hx:60: characters 57-75 : Called from
/home/infidel/haxelib/lime/3,5,2/lime/system/CFFI.hx:47: characters 9-41 : Called from
/home/infidel/haxelib/lime/3,5,2/lime/system/System.hx:18: characters 1-7 : Called from
/usr/share/haxe/std/haxe/macro/Context.hx:381: characters 9-37 : Called from
/usr/share/haxe/std/haxe/macro/ComplexTypeTools.hx:51: characters 28-71 : Called from
/home/infidel/haxelib/lime/3,5,2/lime/_macros/CFFIMacro.hx:60: characters 57-75 : Called from
/home/infidel/haxelib/lime/3,5,2/lime/system/CFFI.hx:47: characters 9-41 : Called from
/home/infidel/haxelib/lime/3,5,2/lime/text/Font.hx:25: characters 1-7 : Called from
```
Looks like the macro loops infinitely for some reason. Removing the font file makes it work.

This might be a lime bug but I don't know how to reproduce it without using HaxePunk.

**Comment by bendmorris** [comment]
Thanks for the detailed report. So far I haven't been able to repro this on a mac - only difference in my setup is that I'm using Haxe 3.3.0.

**Comment by infidel-** [comment]
I'm checking out the 3.4.0 and having compilation problems with macros when using compilation server. So it might be a 3.4.0 thing.

**Comment by bendmorris** [comment]
As I suspected this is an issue with Haxe 3.4.0 and has been reported there: https://github.com/HaxeFoundation/haxe/issues/5918

Other Lime projects are reporting the same issue. Closing this as not an issue with HaxePunk.
