### ISSUE TITLE
Can't connect joystick via Input.joystick()

### ISSUE THREAD

**Issue by johntringham** [HaxePunk/HaxePunk#437]
- **HaxePunk version:** 2.6.0
- **Target(s):** Windows-CPP, Neko
- **Haxe version:** 3.2.0
- **OpenFL/Lime or NME version:** OpenFL 4.5.2, Lime 3.5.2

Hi,

I'm unable to get Input.joystick(x) to return any joysticks, for any value of x.

This did work for older versions of haxepunk/openfl (I was previously using HXP 2.5.6 / OpenFL 3.6.1), but when I updated to the latest, haxepunk stopped registering joysticks.

The controller can be accessed via the [Gamepad api](http://www.openfl.org/blog/2015/10/06/october-update/) instead, so this issue can be worked around, but it's a pain to have to move the logic over.

Sample code: (also contains the working lime.ui.Gamepad version to compare, to double check I wasn't going crazy and forgetting to plug in the controller)

```
import com.haxepunk.Scene;
import com.haxepunk.utils.Input;
import lime.ui.Gamepad;

class MainScene extends Scene
{
    private static var limeGamepads = 0;
    
    public function new()
    {
        super();
        HookupLimeGamepadsEvents();
    }
    
    // Works correctly
    private function HookupLimeGamepadsEvents() : Void
    {
        Gamepad.onConnect.add (function (gamepad : Gamepad) {
            trace ("Connected Gamepad: " + gamepad.name);
            limeGamepads ++;
            
            gamepad.onDisconnect.add (function () {
                trace ("Disconnected Gamepad");
                limeGamepads --;
            });
        });
    }
    
    // Doesn't find any joysticks
    public static function ConnectAndCheckHaxepunkJoysticks()
    {
        for(joyId in 0 ... 1000){
            var joystick = Input.joystick(joyId);
            
            for (i in 0...20){
                var pressed = joystick.check(i);
                if (pressed){
                    trace('Button $i pressed on joystick $joyId'); // Bug - never being hit
                }
            }
        }
    }
    
    public override function update ()
    {
        ConnectAndCheckHaxepunkJoysticks();
        
        trace('No of lime gamepads: $limeGamepads'); // Correctly prints however many you have connected
        trace('No of haxepunk joysticks: ${Input.joysticks}');    // Bug - always 0
    }
 }
```

For me, this spits out:
```
MainScene.hx:48: No of lime gamepads: 1
MainScene.hx:49: No of haxepunk joysticks: 0
```

Is anyone else seeing this?

Thanks,
John

**Comment by bendmorris** [comment]
Unfortunately the Joystick class used `openfl.events.JoystickEvent` which OpenFL seems to have removed. We'll need to rewrite using GameInput. Current workarounds are to use the Lime API directly, or use an older version of OpenFL with `-Dlegacy`.

**Comment by johntringham** [comment]
I thought that'd be the case - I'll use a work around for the time being.

**Comment by bendmorris** [comment]
haxepunk.input.Gamepad in the dev branch now uses Lime's Gamepad API.
