### ISSUE TITLE
Null Object Reference when using Text

### ISSUE THREAD

**Issue by Jacic** [HaxePunk/HaxePunk#445]
- **HaxePunk version:** Any
- **Target(s):** Flash, Linux (probably others too)
- **Haxe version:** 3.4.0
- **OpenFL/Lime or NME version:** Since OpenFL 4.8.0 and Lime 3.7.3

I don't know if anyone is aware of this, but I didn't see an issue created for this.
Using Text causes a crash due to a Null Object Reference since the listed OpenFL/Lime versions. Stack trace:

```
Called from openfl.display.Stage::__broadcastEvent openfl/display/Stage.hx line 1100
Called from openfl.display.DisplayObject::__dispatch openfl/display/DisplayObject.hx line 337
Called from openfl.events.EventDispatcher::__dispatchEvent openfl/events/EventDispatcher.hx line 218
Called from haxepunk.Engine::onEnterFrame haxepunk/Engine.hx line 326
Called from haxepunk.Engine::render haxepunk/Engine.hx line 165
Called from haxepunk.Scene::render haxepunk/Scene.hx line 179
Called from haxepunk.Entity::render haxepunk/Entity.hx line 180
Called from haxepunk.graphics.Text::renderAtlas haxepunk/graphics/Text.hx line 687
Called from haxepunk.graphics.Text::updateTextBuffer haxepunk/graphics/Text.hx line 336
Called from haxepunk.graphics.Text::resize haxepunk/graphics/Text.hx line 477
Called from haxepunk.graphics.Text::createBuffer haxepunk/graphics/Text.hx line 374
Error : Null Object Reference
```

**Comment by Jacic** [comment]
Any progress on this? I haven't been able to do any more investigation, but I'll test any potential fix.

**Comment by bendmorris** [comment]
You listed "HaxePunk version: any" - do you mean this shows up both on the dev branch and 2.6?

I found a regression which broke Text in the dev branch recently, although I don't believe this was the exact error message I saw. Regardless, I have a local fix for that which I'll test tonight.

For 2.6, I haven't seen any issues with Text, and have tested using OpenFL 4.9.1/Lime 4.0.1.

**Comment by Jacic** [comment]
I just re-confirmed: I'm getting a null object reference on HaxePunk 2.6.0, 2.6.1, and the dev branch.

**Comment by Jacic** [comment]
As of the changes the other week, this bug is fixed. 👍
