### ISSUE TITLE
Flicker when switching Scenes

### ISSUE THREAD

**Issue by bendmorris** [HaxePunk/HaxePunk#446]
From the forums: https://forum.haxepunk.com/index.php?topic=1174.msg14481#new

>I noticed that when you switch scene (HXP.scene = new YourScene()) There is a "flash" where you see just the background colour for one frame. And then the scene renders. If you add this trace:
>
>    `trace(_layerList.length);`
>
>To Scene.hx render() function line 160, then when you change scene you can see that there are 0 layers for the first frame.
>
>This flashing gets annoying when your game has multiple little levels.
>
>Not quite sure what the best fix for this will be... Trying not to render a frame if the layers are 0.

**Comment by forgotten-king** [comment]
Wonder what this might be related to. I'll try looking into it further this week if this hasn't already been touched on.
