### ISSUE TITLE
Incompatible with latest OpenFL\Lime libraries

### ISSUE THREAD

**Issue by SunShiranui** [HaxePunk/HaxePunk#447]
- **HaxePunk version:** 2.6.0
- **Target(s):** neko
- **Haxe version:** 3.2.1
- **OpenFL/Lime or NME version:** lime 4.0.1, openfl 4.9.1

Trying to compile a project with "lime test neko" returns the following:

> /usr/lib/haxe/lib/HaxePunk/2,6,0/com/haxepunk/graphics/atlas/HardwareRenderer.hx:258: characters 35-41 : lime.utils.Float32Array should be Int
> 
> /usr/lib/haxe/lib/HaxePunk/2,6,0/com/haxepunk/graphics/atlas/HardwareRenderer.hx:258: characters 35-41 : For function argument 'size'
> 
> /usr/lib/haxe/lib/HaxePunk/2,6,0/com/haxepunk/graphics/atlas/HardwareRenderer.hx:311: characters 55-60 : Bool should be Int
> 
> /usr/lib/haxe/lib/HaxePunk/2,6,0/com/haxepunk/graphics/atlas/HardwareRenderer.hx:311: characters 55-60 : For function argument 'count'
> 
> /usr/lib/haxe/lib/HaxePunk/2,6,0/com/haxepunk/graphics/atlas/HardwareRenderer.hx:335: characters 40-46 : lime.utils.Float32Array should be Int
> 
> /usr/lib/haxe/lib/HaxePunk/2,6,0/com/haxepunk/graphics/atlas/HardwareRenderer.hx:335: characters 40-46 : For function argument 'size'

**Comment by bendmorris** [comment]
Lime 4 is a new major version with breaking changes and was just released a week ago. Since the next version of HaxePunk will be a major release as well, I need to evaluate whether the changes to support Lime 4 will be simple enough to backport to 2.6. There doesn't seem to be a particularly strong incentive to upgrade, just some changed APIs. For now I would recommend sticking with Lime 3.

**Comment by bendmorris** [comment]
Update: changes are relatively simple, should be possible to backport these and put out a 2.6.1 patch release with Lime 4 support.

**Comment by bendmorris** [comment]
Just pushed HaxePunk 2.6.1 to haxelib which was tested with OpenFL 4.9.1 and Lime 4.0.1.

**Comment by Jacic** [comment]
I just tested it with OpenFL 4.9.1 and Lime 4.0.2 and it works fine.

**Comment by bendmorris** [comment]
Thanks for confirming!
