### ISSUE TITLE
Compile error: [Assets.hx] There is no asset library named ""

### ISSUE THREAD

**Issue by voec** [HaxePunk/HaxePunk#449]
- **HaxePunk version:** 2.6.0
- **Target(s):** neko, html5, flash, cpp-windows
- **Haxe version:** 3.4.0
- **OpenFL / Lime:** 3.6.1 / 2.9.1

I'm getting the following error when trying to compile:

```
Assets.hx:246: [Assets] There is no asset library named ""
Assets.hx:316: [Assets] There is no asset library named ""
AL lib: (EE) alc_cleanup: 1 device not closed
```

It only happens when I try to include any asset like `new Image("assets/test.png")`.
And it only occurs in 2.6.0.
Changing back to HaxePunk 2.5.6 (with same OpenFl / Lime version) compiling works without a problem.
The haxepunk examples won't compile either, so it's not an issue with my project specific.

Any ideas?

**Comment by bendmorris** [comment]
I'm not able to repro this, using all the same versions but on Linux. I'm not sure what could've changed between 2.5.6 and 2.6.0 that would break asset loading.

**Comment by bendmorris** [comment]
At the moment there doesn't seem to be anything actionable, but please feel free to reopen if you can help us narrow down the source of the issue.
