### ISSUE TITLE
FPS counter in console

### ISSUE THREAD

**Issue by MattTuttle** [HaxePunk/HaxePunk#454]
- **HaxePunk version:** 4.0.0
- **Target(s):** neko/cpp
- **Haxe version:** 3.4.2
- **OpenFL/Lime or NME version:** OpenFL 4.9.2

There seems to be an issue with the FPS counter in the debug console. When the console is up, using tilde(~), and the play button is pressed the FPS seems to double. It seems like something is processing twice.

**Comment by bendmorris** [comment]
Thanks for the reminder :-/ I think I have a local fix for this sitting around, will submit later tonight.

**Comment by bendmorris** [comment]
https://github.com/HaxePunk/HaxePunk/issues/454
