### ISSUE TITLE
White boxes on startup

### ISSUE THREAD

**Issue by MattTuttle** [HaxePunk/HaxePunk#460]
- **HaxePunk version:** 4.0.0
- **Target(s):** neko/cpp on macOS 10.12
- **OpenFL version:** 4.9.2

When the window is created I get a flash of white boxes on the screen. They look like untextured objects. This doesn't happen in nme so this makes me think it is possibly a bug in openfl. I haven't tested any other platforms so it could also be Mac specific.

**Comment by bendmorris** [comment]
I started noticing this on Linux when I upgraded from Lime 4.0.1 to 4.0.3.

**Comment by Anheurystics** [comment]
I remember encountering this problem a while back, I think it's the HaxePunk preloader being rendered as white squares.

**Comment by bendmorris** [comment]
Unless it changed recently, I don't think the preloader gets shown on desktop targets, right?

**Comment by MattTuttle** [comment]
Oh wow. I think you nailed it.

Looks like OpenFL/Lime has changed the way embedded images work. http://community.openfl.org/t/issue-with-embedded-bitmapdata/9008/14

I'm going to see if using `Assets.loadBitmapData()` fixes it.

**Comment by bendmorris** [comment]
Looks like Assets.loadBitmapData on Lime was the solution.
