### ISSUE TITLE
Text doesn't update if original string is too large

### ISSUE THREAD

**Issue by MattTuttle** [HaxePunk/HaxePunk#473]
If you create a Text instance with a large string it will not update the buffer.

```haxe
var text = new Text("This is a long string");
text.text = "Short string"; // won't update
```

**Comment by bendmorris** [comment]
I wasn't able to repro this locally, which OpenFL/Lime version did you see it on?

There is some split logic where it creates a new buffer when the size gets bigger and not when it gets smaller, but AFAICT that's working correctly, and on a smaller resize it should still clear the buffer and redraw the text.

**Comment by MattTuttle** [comment]
I'm seeing it on openfl 4.9.2 and lime 4.0.3. Here is the class I'm using after doing `haxelib run haxepunk new test`.
```haxe
class MainScene extends Scene
{
	override public function begin()
	{
		var text = new haxepunk.graphics.Text("This is a long string");
		text.text = "Short string";
		addGraphic(text, 0, 100, 100);
	}
}
```

**Comment by bendmorris** [comment]
Looks fine on HTML5:

![screenshot from 2017-04-29 19-39-25](https://cloud.githubusercontent.com/assets/544977/25560838/936b98c6-2d13-11e7-9391-17e9c480965c.png)

But when I run this for neko or C++, I see just a black screen with no text...

![screenshot from 2017-04-29 19-40-24](https://cloud.githubusercontent.com/assets/544977/25560846/b5f7e354-2d13-11e7-84ca-f9690c2f4ea2.png)

**Comment by MattTuttle** [comment]
I believe this was fixed in https://github.com/HaxePunk/HaxePunk/commit/7a6cb844105645d0c860083c90cab7cd91ae1f1d.
