### ISSUE TITLE
[neko] HardwareRenderer.hx:41: GL Error: 1281

### ISSUE THREAD

**Issue by man2** [HaxePunk/HaxePunk#485]
- **HaxePunk version:** 4.0
- **Target(s): neko
- **Haxe version: 3.4.2
- **OpenFL/Lime or NME version:**  openfl : 5.0.0 lime 4.1.0

Got this error spitting out all the time at log for neko target
HardwareRenderer.hx:41: GL Error: 1281

It doesn't affect anything I think, but it makes the log full of this message

**Comment by MattTuttle** [comment]
This is usually caused by an invalid value being passed to the OpenGL shaders. Are you seeing any rendering issues?

**Comment by bendmorris** [comment]
The invalid value could be in OpenFL or Lime. I pushed a commit to show the line that the log came from. If it's the first check in HardwareRenderer, it's probably coming from outside of HaxePunk.

**Comment by man2** [comment]
Think it only happens on Intel HD Graphics ? 

There is no rendering issues

**Comment by man2** [comment]
It's already opened as issue on openfl 
https://github.com/openfl/openfl/issues/1559

**Comment by bendmorris** [comment]
I'll close this, but I'm open to feedback if people think these logs aren't helpful. Currently they only log in debug mode, but maybe there should be a specific opt-in flag instead?
