### ISSUE TITLE
flash package not found

### ISSUE THREAD

**Issue by man2** [HaxePunk/HaxePunk#487]
- **HaxePunk version:** 4.0.0
- **Target(s): Every target
- **Haxe version: 3.4.2
- **OpenFL/Lime or NME version:** openfl : 5.1.0 . lime : 5.0.0

Can be fixed by changing flash package to openfl. Can we do the change?

**Comment by bendmorris** [comment]
[This line](https://github.com/openfl/openfl/blob/develop/include.xml#L43) in OpenFL's include.xml should make importing from `flash` work:

`<haxeflag name="--remap" value="flash:openfl" />`

I've been using `flash.*` imports forever, so I'm assuming if you revert to something < lime 5.0 it works?

This sounds like an issue with Lime's build tool, I would report it over there.

**Comment by man2** [comment]
I assume it will work on lime prior to 5.0 because this problem has just appeared after upgrading lime to 5.0.0

**Comment by man2** [comment]
adding 
<haxeflag name="--remap" value="flash:openfl" />

Still doesn't work.

F:/development/haxelib/HaxePunk/haxepunk/debug/Console.hx:6: characters 7-19 : Type not found : flash.Assets

**Comment by man2** [comment]
problem is only on Flash target apparently, tried building for neko target, no problem

**Comment by bendmorris** [comment]
Ah, that would be it then. Starting in 4.0 we're dropping support for the Flash target (see the [changelog](https://github.com/HaxePunk/HaxePunk/blob/dev/CHANGELOG.md)). Neko works for fast iteration, and HTML5/WebGL works for web.

**Comment by man2** [comment]
I see, it should be closed then
