### ISSUE TITLE
[request] vscode project support

### ISSUE THREAD

**Issue by qntf** [HaxePunk/HaxePunk#500]
HaxeFlixel has [VSCode](https://github.com/HaxeFlixel/flixel-templates/tree/dev/ide-data/visual-studio-code) support in their templates.

I think VSCode would be a great IDE for development because it's Haxe extension is pretty good at this point, giving us full language and completion support, there's a mostly working HXCPP debugger, and it's an open source cross-platform editor.

**Comment by bendmorris** [comment]
I agree that it would be useful. I'm not sure when I will get to this, so a pull request would be welcome!
