### ISSUE TITLE
Graphic.hx:53: characters 2-27 : haxepunk.graphics.atlas.AtlasRegion should be haxepunk.ImageType

### ISSUE THREAD

**Issue by wselken** [HaxePunk/HaxePunk#510]
- **HaxePunk version:** dev latest
- **Target(s):** neko or linux
- **Haxe version:** [3.4.64]
- **OpenFL/Lime or NME version:** [5.4.0]

I'm getting a build issue. graphic is not working: haxepunk.graphics.atlas.AtlasRegion should be haxepunk.ImageType

**Comment by bendmorris** [comment]
Strange...this looks like a pretty fundamental issue, but I'm not seeing it myself and it's not showing up on Travis (Haxe 3.4.2). Perhaps a Haxe regression?

As you can see here: https://github.com/HaxePunk/HaxePunk/blob/dev/haxepunk/Graphic.hx#L55 we do define a conversion from IAtlasRegion to ImageType.

**Comment by wselken** [comment]
Would return fromAtlasRegion(atlas.getRegion(0)); be an acceptable solution. Seems to stop the build issue, but I'm running into a separate issue with the input handlers, so can't test.  Is this an appropriate place to bring up bugs like these?

**Comment by bendmorris** [comment]
It is an appropriate place - just want to narrow down the cause, vs. a regression somewhere outside of HaxePunk. As a workaround you can always call the ImageType conversion methods yourself if the implicit conversion isn't working (`new Image(ImageType.fromAtlasRegion(region))`).

I'm also curious if changing the parameter from `region:IAtlasRegion` to `region:AtlasRegion` would solve your issue.

**Comment by wselken** [comment]
reverting to haxe 3.4.2 doesn't seem to resolve the issue. perhaps a regression in lime? Is this a problem of me calling fromTileAtlas, i just thought graphic wasn't building because it thinks the return value mismatches function.

changing the parameter from region:IAtlasRegion to region:AtlasRegion causes more errors:
Graphic.hx:53: characters 2-27 : haxepunk.graphics.atlas.AtlasRegion should be haxepunk.ImageType
Graphic.hx:57: characters 2-15 : haxepunk.graphics.atlas.AtlasRegion should be haxepunk.ImageType
Graphic.hx:69: characters 2-32 : haxepunk.graphics.atlas.AtlasResolutions should be haxepunk.ImageType

**Comment by wselken** [comment]
using lime [5.4.0], looks like i put the wrong version in the original comment.

**Comment by wselken** [comment]
was using haxe 3.2.1.  Updated to 3.4.2. now it works. sorry.
