### ISSUE TITLE
Input.hx Complians about abstract value

### ISSUE THREAD

**Issue by wselken** [HaxePunk/HaxePunk#511]
- **HaxePunk version:** dev latest
- **Target(s):** neko or linux
- **Haxe version:** [3.4.64]
- **OpenFL/Lime or NME version:** [5.4.0]

I'm getting a build issue. Input.hx is complaing.  haxepunk/input/Input.hx:19: characters 51-54 : Cannot use abstract as value.
It has a problem with the abstract key and mouse classes in the dynamic array.
public static var handlers:Array<InputHandler> = [Key, Mouse];  Any thoughts?

**Comment by bendmorris** [comment]
>Haxe version: [3.4.64]

Is that right? I don't see any such version; last release was 3.4.2.

This used to work (using an impl class with static functions to satisfy the InputHandler typedef) and does locally for me. If you can confirm the version of Haxe you're using, I'll try to verify.

**Comment by wselken** [comment]
my bad. i looking at hxcpp.  My haxe version 3.2.1. Updated to 3.4.2. now it works. sorry.
