### ISSUE TITLE
Entity.setHitboxTo broken on HTML5

### ISSUE THREAD

**Issue by IkonOne** [HaxePunk/HaxePunk#514]
- 4.0.0
- HTML5
- 3.4.4
- openfl: 6.2.2

Issue location: https://github.com/HaxePunk/HaxePunk/blob/dev/haxepunk/Entity.hx#L650
Reproduce:
`entity.setHitboxTo(anyGraphicWithoutOrigin);`

That line does not behave as expected on HTML5 when the property does not exist.  Expected result would be Std.int(null) would throw an error so that the getInt function returns the default value, but it actually returns 0: https://try.haxe.org/#D2eb6

This is probably a haxe bug and not Haxepunk.

http://api.haxe.org/Std.html#int

**Comment by forgotten-king** [comment]
@IkonOne Do you have a small code snippet where this fails? What "graphic without orientation" code is causing the issue?

Then the easiest approach(workaround or fix?), I assume, would be to add some HTML5 guards to prevent this from happening. Looking at the code you pointed out as being the problem -- it's not pointing at "setHitboxTo". 

So like you said, maybe inside the try block, there can be an HTML5 guard which, for now, checks if it is null and returns the default.
