### ISSUE TITLE
Error in building(newly installed)

### ISSUE THREAD

**Issue by flamendless** [HaxePunk/HaxePunk#519]
- HaxePunk 2.6.1
- OpenFL - 6.4; Lime-5.8.1; nme -6.058
After following the guide in the site, i encountered errors when using "lime test neko".
Here is the error:
`haxe
D:/Haxe/haxe/lib/HaxePunk/2,6,1/com/haxepunk/graphics/atlas/HardwareRenderer.hx:7: characters 7-19 : Type not found : openfl.gl.GL
D:/Haxe/haxe/lib/HaxePunk/2,6,1/com/haxepunk/graphics/atlas/SceneSprite.hx:10: lines 10-84 : Defined in this class
D:/Haxe/haxe/lib/HaxePunk/2,6,1/com/haxepunk/graphics/atlas/SceneSprite.hx:27: characters 2-10 : Void is not a value
D:/Haxe/haxe/lib/HaxePunk/2,6,1/com/haxepunk/graphics/atlas/SceneSprite.hx:46: characters 2-10 : Void is not a value
`

**Comment by bendmorris** [comment]
Thanks for reporting. The gl package moved from openfl to lime, I think around OpenFL 6. I'll patch this on the 2.6 branch.

**Comment by flamendless** [comment]
How would i fix it in my setup?

**Comment by Kasparsu** [comment]
this should not be an issue anymore. I installed haxepunk on both linux and windows without any issues what so ever
