### ISSUE TITLE
Entity Layer Doc-Clarification

### ISSUE THREAD

**Issue by forgotten-king** [HaxePunk/HaxePunk#521]
- **HaxePunk version:** Dev

The [documentation for Layers](https://github.com/HaxePunk/HaxePunk/blob/4278f0041ff6a49b729c39db1066e107d15b4f77/haxepunk/Entity.hx#L546) is a bit cryptic to me. Although, after investigating further, it was apparent, I believe that it should be more clearly defined. 

"Rendered first" isn't very helpful visually, and "higher layers" is kind of vague. 

How about replacing it along the lines of: **... Layers are drawn in a descending order. Backgrounds should have large(positive) numbers, foregrounds will have small(negative) numbers.**

**Comment by bendmorris** [comment]
How about a pull request? For something this simple, click "edit this file" in GitHub and it'll automatically make a PR with your edits.

**Comment by forgotten-king** [comment]
Thanks! I will go ahead and do so :)
