### ISSUE TITLE
BitmapText with Unicode text gives error on Android

### ISSUE THREAD

**Issue by eliolanda** [HaxePunk/HaxePunk#537]
- **HaxePunk version:** git version
- **Target(s):** Android
- **Haxe version:** 3.4.4
- **OpenFL/Lime:** 6.1.2/5.5.0

BitmapText with Chinese (and any other Unicode) chars works fine for HTML5 target, but for Android it crashes with error: 
`E/Exception(25389): "font/font.fnt" is not a valid .fnt file!`

[BitmapTextTest.zip](https://github.com/HaxePunk/HaxePunk/files/1642568/BitmapTextTest.zip)

**Comment by eliolanda** [comment]
Changing all `Sting` variables to `UTF8String` in `BitmapFontAtlas `and `BitmapText` fixes issue.

**Comment by bendmorris** [comment]
Awesome. Where is `UTF8String` defined? I only know of [`haxe.Utf8`](https://api.haxe.org/haxe/Utf8.html)

**Comment by eliolanda** [comment]
I've used this abstract: `lime.text.UTF8String`

**Comment by bendmorris** [comment]
Got it. We don't want to depend on `lime` for this but we can add our own abstract to make it easy to interchange with String.

**Comment by bendmorris** [comment]
@eliolanda - I updated BitmapText to use a new haxepunk.utils.Utf8String abstract. It worked in my initial tests, can you let me know if this resolves your issue?

**Comment by bendmorris** [comment]
Pushed another fix. I was able to repro your issue using the provided font, and after this change was able to parse the font successfully.

**Comment by eliolanda** [comment]
BitmapText.hx -> line 75 ->  TextBlock(text:String);
should be 	TextBlock(text:Utf8String);
before that fix BitmapTextTest doesn't work for me for neko / Android targets.
