### ISSUE TITLE
hardware Renderer (openfl.gl.GL)  problem

### ISSUE THREAD

**Issue by FlamingQuasar** [HaxePunk/HaxePunk#548]
HaxeCompiler 3.4.4
- **HaxePunk version:** 2.6.1
- **Target(s):** windows
- **Haxe version:** 3.4.4
- **OpenFL/Lime or NME version:** up to 7.0.0 OpenFL/ up to 6.0.1 Lime 

Problem with solving atlas exceptions problems with hardware Renderer (openfl.gl.GL)
while compiling game on windows (on no graphics-card laptop)

run lime build  <...> windows -release -Dfdb
C:/HaxeToolkit/haxe/lib/HaxePunk/2,6,1/com/haxepunk/graphics/atlas/HardwareRenderer.hx:7: characters 7-19 : Type not found : openfl.gl.GL
C:/HaxeToolkit/haxe/lib/HaxePunk/2,6,1/com/haxepunk/graphics/atlas/SceneSprite.hx:10: lines 10-84 : Defined in this class
C:/HaxeToolkit/haxe/lib/HaxePunk/2,6,1/com/haxepunk/graphics/atlas/SceneSprite.hx:46: characters 2-10 : Void is not a value
C:/HaxeToolkit/haxe/lib/HaxePunk/2,6,1/com/haxepunk/graphics/atlas/SceneSprite.hx:75: characters 4-12 : Void is not a value
Build halted with errors.

**Comment by bendmorris** [comment]
You listed "up to 7.0.0 OpenFL" but I believe `openfl.gl.GL` was removed in OpenFL 6.0. If you use a 5.X or earlier version of OpenFL and compatible version of Lime, does it work?

The dev branch (upcoming 4.0 release) supports the latest version of OpenFL via better abstractions. 2.6 is more limited in what it can support.

**Comment by bendmorris** [comment]
Closing; please let me know if you still encounter this issue either on HaxePunk 4.0+, or on 2.6 with pre-6.0 versions of OpenFL.
