### ISSUE TITLE
Gamepad.onConnect is not being called

### ISSUE THREAD

**Issue by gmisail64** [HaxePunk/HaxePunk#559]
- HaxePunk 4.0.0
- Neko
- Haxe 3.4.4
- OpenFL 7.1.1, Lime 6.1.0

When using gamepads with HaxePunk, the gamepad is currently **detected** however Gamepad does not emit the onConnect signal. 

```
    Gamepad.onConnect.bind(onGamepadConnect); //earlier in my code

    private static function onGamepadConnect(gamepad : Gamepad)
    {
        trace("connect");
    }
```

I am currently printing the number of gamepads per frame in my update function. When I plug in my controller (PS3 & Xbox One) the number of the gamepads increases by 1, however the onConnect signal is never emitted.

**Comment by bendmorris** [comment]
It looks like we're not properly initializing gamepad input at app startup. As a temporary workaround you can call `haxepunk._internal.GamepadInput.init(HXP.app)` when your project starts up. I'll get a proper fix in the next patch release.

**Comment by TheSpydog** [comment]
I have the same Haxe/OpenFL/Lime setup but I'm not seeing this behavior. I wrote a [small test scene](https://gist.github.com/TheSpydog/c9f92d3c87d0d7294c163bf46f6384bb) and tested it with my wired PS4 controller. It behaved as expected. Does this scene still exhibit the behavior you described?

**Comment by gmisail64** [comment]
It is working fine with my PS4 controller, it must have been something with my PS3 controller I guess. Are there any PS4 bindings, or will the PS3 ones do? I assume they won't, at least from my tests.

**Comment by TheSpydog** [comment]
I couldn't find any PS4 bindings, so I made some. [Here's a first shot at a PS4 Gamepad class.](https://gist.github.com/TheSpydog/92de27a78dc0a454f7158ae208050dd7) I'm not sure if this will work on different platforms (I only tested on Mac), but it might help you get started at least. Let me know if it works! I'd like to get PS4 bindings officially added to the project soon.

Also, you said that the onConnect signal didn't fire with the Xbox One controller either, right? That still leaves me concerned that this is a deeper issue than just a wonky PS3 controller.

**Comment by gmisail64** [comment]
I know that HaxeFlixel has working PS4 and Xbox One bindings, at least on Mac. I have no experience using their bindings on Windows. 

PS4 onConnect / Disconnect signals are good. I just tested with the Xbox One controller and everything is working well. I'm not sure what the original issue was then. There is still the issue of creating bindings for Xbox One and PS4.

**Comment by bendmorris** [comment]
Ideally, I'd like to outsource this to a separate library (or repo, if we build it ourselves) rather than maintain a lot of button mappings in the main repo. Ideally HaxePunk would only deal with an abstract set of buttons (button 1-4, dpad, etc.) and a separate library would map those to specific button codes based on the type of controller plugged in (which we also don't have a way to detect right now.)
