### ISSUE TITLE
Default icon scales poorly

### ISSUE THREAD

**Issue by TheSpydog** [HaxePunk/HaxePunk#561]
- **HaxePunk version:** 4.0.0
- **Target(s):** Lime, HTML5
- **Haxe version:** 3.4.4
- **OpenFL/Lime or NME version:** 7.1.1/6.1.0

When running a game on macOS, the default icon included in the template (HaxePunk.svg) appears very small and shifted to the upper-left of its space in the Dock. The .png version appears distorted and smushed. Perhaps these images could be replaced with a square image of the cog-heart like the GitHub avatar:
![](https://avatars3.githubusercontent.com/u/4005742?s=200&v=4)

**Comment by JavierRizzoA** [comment]
This issue also affects Android.

![2018-02-12 20 42 43](https://user-images.githubusercontent.com/1953021/36134313-e247ab52-1038-11e8-9b6e-ba81ad7e1d9d.jpg)

**Comment by bendmorris** [comment]
Definitely meant to include the square version of the icon, but when I swapped it in, it still doesn't look right. For some reason OpenFL is squashing it into the top left corner of its generated favicon.png:

![image](https://user-images.githubusercontent.com/544977/36134783-e48b5d2a-103b-11e8-9e9e-bc30af1bea9a.png)

May be an OpenFL bug, looking into it.

**Comment by bendmorris** [comment]
It is a bug with SVG icons in OpenFL: https://github.com/openfl/openfl/issues/916

In the meantime I'll use a PNG, although the quality seems lower.

**Comment by bendmorris** [comment]
Fixed in b382c9e

**Comment by TheSpydog** [comment]
Changing the width and height properties in the SVG from 256 to 64 fixed the top-left squashing issue for me. Not sure why.
