### ISSUE TITLE
Default project.xml includes *.mp3 assets when targeting flash (and flash is not supported anymore)

### ISSUE THREAD

**Issue by JavierRizzoA** [HaxePunk/HaxePunk#563]
- **HaxePunk version:** 4.0.0
- **Target(s):** N/A
- **Haxe version:** Any
- **OpenFL/Lime or NME version:** Any

The line

```
	<assets path="assets/audio" rename="audio" include="*.mp3" if="flash"/>
```
on the default `project.xml` should be removed because flash is not supported anymore.

For the same reason,
```
	<assets path="assets/audio" rename="audio" include="*.wav|*.ogg" unless="flash"/>
```
should drop the `unless`.

**Comment by bendmorris** [comment]
Fixed in b382c9e
