### ISSUE TITLE
Problems with variables not found in haxepunk

### ISSUE THREAD

**Issue by reaperspeeds** [HaxePunk/HaxePunk#565]
Hi, I'm having trouble with the variables that were in haxepunk version 2.6.1 as they are:

HXP. stage was not found
Image. createPolygon was not found
currentAnim in Spritemap to know what animation you are currently in
Event Resize on the scene is now a signal, I don't know how to change it.

Can you help me find out where these variables are in the new update?

- **HaxePunk version: 4.0.0
- **Target(s): html5, android, neko
- **Haxe version: 3.4.4
- **OpenFL/Lime  version  7.1.1 /6.0.1

**Comment by bendmorris** [comment]
- You can get the stage directly from OpenFL: `openfl.Lib.current.stage`
- `Image.createPolygon` is no longer supported.
- Spritemap has `currentAnimation`
- Signals are quite easy to use:

```haxe
function resizeFunction() {
    // ...
}

myScene.onResize.bind(resizeFunction);
```

**Comment by bendmorris** [comment]
As these are questions and not issues with HaxePunk, if you have any more, please feel free to ask over on [Gitter](https://gitter.im/HaxePunk/HaxePunk) (recommended) or the [forum](https://forum.haxepunk.com/).
