### ISSUE TITLE
Position and math.Vector2 classes seem redundant

### ISSUE THREAD

**Issue by TheSpydog** [HaxePunk/HaxePunk#566]
- **HaxePunk version:** 4.0.0
- **Target(s):** N/A
- **Haxe version:** 3.4.6
- **OpenFL/Lime or NME version:** 7.1.1/6.1.0

Several methods in the MathUtils class use the Position abstract type for their parameters instead of Vector2. I don't understand why, since Vector2 represents the same concept and has more features. Additionally, in my testing, the compiler cannot implicitly cast Entities into Position types anyway, so the abstraction doesn't seem to offer any benefits.

Perhaps the MathUtils could be rewritten to take Vector2s, and Vector2s could be implicitly cast from Entities? This may be a breaking change, though.

**Comment by bendmorris** [comment]
The reason is that `Vector2` is a class, so if the methods accepted Vector2, you'd need to create one for your Entity. The idea is for things like Entities to be able to use these methods without an extra allocation; why this doesn't currently work for Entity without a special `@:from` method is worth looking into (maybe it's due to the getter/setter?)

**Comment by TheSpydog** [comment]
Isn't a `Position` being allocated anyway, or does something else happen because it's abstract? I'm still fuzzy on how typedefs, abstracts, and implicit casting work, even after reading through the Haxe documentation several times. Also, in the current implementation of Position it looks like the `@:from` only converts from `PositionData` to `Position`. Is `Entity` supposed to be interpreted as a `PositionData` just because it contains an `x` and `y` property?

**Comment by bendmorris** [comment]
>Is Entity supposed to be interpreted as a PositionData just because it contains an x and y property?

Exactly.

A structural definition like `{x: Float, y: Float}` will unify not only with structures, but also with objects which have that set of fields.

Example

```haxe
typedef Position = {
    x: Float,
    y: Float,
}

class MyClass {
    public var x:Float = 1;
    public var y:Float = 3;
    public function new() {}
}

class Test {
    public static function main() {
        myFunc(new MyClass());
    }

    static function myFunc(v:Position) {
        trace('X: ${v.x}, Y: ${v.y}');
    }
}
```

Result:

```
>>> haxe -main Test --interp
Test.hx:18: X: 1, Y: 3
```

I'm guessing the problem might be that Entity isn't just `public var x:Float;`, it's `@:isVar public var x(get, set):Float;`.

**Comment by TheSpydog** [comment]
Oh, okay. That makes sense! Thanks for the explanation. I'll experiment with the getters and setters in Entity and see if I can get it to work as expected.

**Comment by TheSpydog** [comment]
Your guess was correct. The conversion does not take place because Entity uses properties and not just class variables. If we change the PositionData definition to use properties:

```
private typedef PositionData =
{
	@:isVar var x(get, set):Float;
	@:isVar var y(get, set):Float;
};
```

Then Entity can be used in the MathUtil methods. However...because these are properties and not simple variables, you can no longer pass anonymous `{x: 0, y: 0}` objects to the methods. I haven't found a way to allow for these kinds of objects as well.
