### ISSUE TITLE
Build fails while following the Getting Started guide

### ISSUE THREAD

**Issue by Kinrany** [HaxePunk/HaxePunk#579]
(Lime version and Lime command line tool version are the same, right?)

- **HaxePunk version:** 4.0.1
- **Target:** N/A
- **Haxe version:** 3.3.0
- **OpenFL version:** 7.1.2
- **Lime version:** 6.2.0
- **OS:** Windows 7

I'm trying to follow the [Getting Started](http://haxepunk.com/documentation/tutorials/getting-started/) guide.

`lime test neko` fails with this error:

```
C:/Programs/HaxeToolkit/haxe/lib/HaxePunk/4,0,1/haxepunk/graphics/hardware/opengl/GLUtils.hx:39: characters 43-46 : Type not found : Any
```

I also had to run `haxelib install lime` after running `haxelib install openfl`, even though the guide only mentions the latter.

**Comment by matrefeytontias** [comment]
You need at least Haxe 3.4.0 for this to work. `Any` was introduced on that version.

**Comment by Kinrany** [comment]
Oh. Turns out I had more than one version installed, thanks.
