### ISSUE TITLE
Type not found : lime.graphics.GLRenderContext

### ISSUE THREAD

**Issue by increpare** [HaxePunk/HaxePunk#606]
- **HaxePunk version:** 4.0.1
- **Target(s):** neko
- **Haxe version:** 3.4.7
- **OpenFL/Lime or NME version:** 8.4.1-LlyE3A

following the guidelines on http://haxepunk.com/documentation/tutorials/getting-started/ I get the following errors

```/usr/local/lib/haxe/lib/HaxePunk/git/backend/lime/haxepunk/graphics/hardware/opengl/GLInternal.hx:5: characters 7-36 : Type not found : lime.graphics.GLRenderContext
/usr/local/lib/haxe/lib/HaxePunk/git/haxepunk/graphics/hardware/opengl/GLUtils.hx:6: lines 6-43 : Defined in this class
/usr/local/lib/haxe/lib/HaxePunk/git/haxepunk/graphics/hardware/opengl/GLUtils.hx:41: characters 9-27 : Class<haxepunk.graphics.hardware.opengl.GLInternal> has no field invalid
/usr/local/lib/haxe/lib/HaxePunk/git/backend/lime/haxepunk/App.hx:19: characters 3-56 : Class<haxepunk.graphics.hardware.opengl.GLInternal> has no field renderer
/usr/local/lib/haxe/lib/HaxePunk/git/backend/lime/haxepunk/App.hx:20: characters 3-50 : Class<haxepunk.graphics.hardware.opengl.GLInternal> has no field gl```

**Comment by bendmorris** [comment]
Lime version? We've tested with OpenFL 8.0.0 and Lime 6.3.0. Anything more recent than that isn't guaranteed to work.

**Comment by increpare** [comment]
Ah ok, downgrading fixed it. (Worth considering adding that to the setup guide?)  (the old version I had was very likely 7.0.0, but now that it's working I don't want to mess with it any more )

**Comment by Ghouly-The-Ghost** [comment]
This has been fixed but it is not merged into dev or master. @matrefeytontias

**Comment by matrefeytontias** [comment]
The fix comes with a new unreleased Lime version (they fixed something on their end). I'll merge and update dependencies when it comes out. I'll keep this open in the meantime.
