### ISSUE TITLE
HTML5 rendering issue

### ISSUE THREAD

**Issue by Jacic** [HaxePunk/HaxePunk#623]
- **HaxePunk version:** git
- **Target(s):** HTML5
- **Haxe version:** 3.4.7
- **OpenFL/Lime or NME version:** OpenFL 8.9.1 and Lime 7.5.0

I decided to try the latest git version after commit [189c003](https://github.com/HaxePunk/HaxePunk/commit/189c0036b642b33cfcc7b41a34bbd0217ce7f85b) fixed compile errors with the latest OpenFL/Lime versions. I tested on Linux, and found no issues with native builds, but on HTML5 rendering appears completely broken.

Here is a screenshot from Firefox:
![Screenshot_20190704_154916](https://user-images.githubusercontent.com/2702803/60687465-69cdca00-9e74-11e9-992d-8836ec172a3a.png)

The rectangle near the top is the HaxePunk debug buttons. I went back to HaxePunk 4.0.1 and OpenFL/Lime 8.0.0/6.3.0 just to make sure there was nothing wrong with my code, and this issue did not occur.

Here also is the asteroids example in html5, showing similar rendering issues:
![Screenshot_20190704_160127](https://user-images.githubusercontent.com/2702803/60687597-1c059180-9e75-11e9-9c32-105c1c5f238f.png)

The Firefox developer console did not show any errors for either app.

**Comment by matrefeytontias** [comment]
Lime has a bug on their end that was made explicit partly thanks to the commit you mentionned. I would advise either against using the latest git version of HaxePunk until a new version of Lime comes out, or switching to the current git version of Lime, in which case everything should be fine. Sorry for the inconvenience.

**Comment by matrefeytontias** [comment]
On second thought, I will comment and close this when a more definitive solution comes out.

**Comment by XANOZOID** [comment]
I'll update the getting started page this weekend, for sure this time lol, to address the HaxePunk versions and compatibilities limbo we're in. Hopefully, it'll help mitigate frustrating discoveries like this going forward.

**Comment by XANOZOID** [comment]
@Jacic this should be fixed now, can you take a look again? The fixed lime version got released and Lime is on version 7.6.3 now.

**Comment by Jacic** [comment]
I got a chance to try out lime 7.6.3, and I can confirm that rendering works how it should.

Thanks.
