### ISSUE TITLE
Broken Build on Latest OpenFL

### ISSUE THREAD

**Issue by XANOZOID** [HaxePunk/HaxePunk#634]
Currently can't compile for OpenFL because GLInternal and App.hx (Lime backend) are using an OpenFL API that was in testing and got scrapped back to its previous version. 

- OpenFL: 9.0.2
- Lime: 7.8.0
- Haxe 4.1.4

Choices for solutions: 
- #632 (with guards)
- #633 (just removing the updated code)

**Comment by matrefeytontias** [comment]
Fixed by #638
