### ISSUE TITLE
Type not found : openfl._internal.renderer.context3D.Context3DRenderer

### ISSUE THREAD

**Issue by fedorabits** [HaxePunk/HaxePunk#635]
- **HaxePunk version:** 4.0.1
- **Target(s):**all
- **Haxe version:**4.2.3
- **OpenFL/Lime or NME version:** 8.9.1

When attempting to test a project, this occurs. I'm not even trying to run anything 3d.

C:/HaxeToolkit/haxe/lib/HaxePunk/git/backend/lime/haxepunk/graphics/hardware/opengl/GLInternal.hx:10: characters 29-82 : Type not found : openfl._internal.renderer.context3D.Context3DRenderer
C:/HaxeToolkit/haxe/lib/HaxePunk/git/haxepunk/graphics/hardware/opengl/GLUtils.hx:6: lines 6-43 : ... Defined in this class
C:/HaxeToolkit/haxe/lib/HaxePunk/git/haxepunk/graphics/hardware/opengl/GLUtils.hx:41: characters 21-28 : Class<haxepunk.graphics.hardware.opengl.GLInternal> has no field invalid
C:/HaxeToolkit/haxe/lib/HaxePunk/git/haxepunk/assets/AssetMacros.hx:28: characters 67-69 : Unknown identifier : id
C:/HaxeToolkit/haxe/lib/HaxePunk/git/haxepunk/assets/AssetMacros.hx:28: characters 67-69 : ... For function argument 's'
C:/HaxeToolkit/haxe/lib/HaxePunk/git/haxepunk/assets/AssetCache.hx:200: characters 10-98 : ... Called from macro here
C:/HaxeToolkit/haxe/lib/HaxePunk/git/backend/lime/haxepunk/App.hx:19: characters 17-70 : Type not found : openfl._internal.renderer.context3D.Context3DRenderer
C:/HaxeToolkit/haxe/lib/HaxePunk/git/backend/lime/haxepunk/App.hx:24: characters 49-57 : Class<haxepunk.graphics.hardware.opengl.GLInternal> has no field renderer

**Comment by matrefeytontias** [comment]
Fixed by #638
