### ISSUE TITLE
Does the current dev version of HaxePunk work with Haxe 4.x?

### ISSUE THREAD

**Issue by JordanMagnuson** [HaxePunk/HaxePunk#636]
Documentation question. I'm looking to start a HaxePunk project (porting some old FlashPunk games), and wondering if I can/should use the latest HaxePunk dev with Haxe 4.x, or should stick with the old HaxePunk 4.0.1 release and Haxe 3.x? I couldn't find any documentation on this, but saw a number of commits in the HaxePunk dev branch related to Haxe 4.

**Comment by matrefeytontias** [comment]
I honestly don't remember. Give me a few days and I'll run a couple checks to make sure everything is in a usable state.

**Comment by JordanMagnuson** [comment]
Thanks for looking into this! 

A related follow-up question would be, if using the stable HaxePunk 4.0.1 release, which version of Haxe 3 is recommended? The last release (Haxe 3.4.7 from 2018-02-22), or Haxe 3.2.x (2015-10-12), the latest version mentioned in the HaxePunk readme?

**Comment by matrefeytontias** [comment]
Whichever combination of library versions is mentioned in the documentation will always work, so that's always a sure shot if you want to get started immediately. You can alternatively try with more recent versions of everything but you'll be on your own on this front.

**Comment by matrefeytontias** [comment]
Fixed by #638
